server.port=${PORT:8080}
logging.level.com.example.helloworld.FlightsController=DEBUG
opensky.username=${OPENSKY_USERNAME:}
opensky.password=${OPENSKY_PASSWORD:}
logging.level.com.example.helloworld.FlightsController=DEBUG
